"""Type stubs for the Rust extension module built from crates/hazres-py.

``geometry`` is ``(left, top, cell_width, cell_height)`` of a north-up grid,
in the grid's own CRS. Points and corners are given in that CRS too.
"""

import numpy as np
import numpy.typing as npt

Geometry = tuple[float, float, float, float]
F32 = npt.NDArray[np.float32]
F64 = npt.NDArray[np.float64]
I32 = npt.NDArray[np.int32]
I64 = npt.NDArray[np.int64]

def engine_version() -> str: ...
def nearest(values: F32, geometry: Geometry, xs: F64, ys: F64) -> F32: ...
def nearest_class(values: I32, geometry: Geometry, xs: F64, ys: F64) -> I32: ...
def bilinear(values: F32, geometry: Geometry, xs: F64, ys: F64) -> F32: ...
def cubic(values: F32, geometry: Geometry, xs: F64, ys: F64) -> F32: ...
def area_weighted(values: F32, geometry: Geometry, corners_x: F64, corners_y: F64) -> F32: ...
def area_majority(values: I32, geometry: Geometry, corners_x: F64, corners_y: F64) -> I32: ...
def cell_index(geometry: Geometry, shape: tuple[int, int], xs: F64, ys: F64) -> I64: ...
def zonal_mean(values: F32, zones: I64, n_zones: int) -> tuple[F64, npt.NDArray[np.uint64]]: ...
def match_zone_means(values: F32, zones: I64, target: F64) -> F32: ...
def block_mean(values: F32, factor: int, min_valid: float) -> F32: ...
def block_majority(values: I32, factor: int) -> I32: ...
